main
js-tasks-ru/js-20201030_hitriysprut pull request #3
Opened 2020-11-17 15:43 UTC by HitriySprut

fixed sortStrings
added tasks 3 and 4

2020-11-17 16:40 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-19 00:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
- should be rendered correctly
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
- should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-11-19 22:42 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const pathNodes = path.split('.');
помните мы проходили замыкания?
Вот было бы неплохо реализовать. получение значения `pathNodes` через замыкание

2020-11-19 22:43 UTC, dosandk approved these changes
работы выглядят хорошо, только пожалуйста не увлекайтесь использованием геттером, в подавляющем большинстве случаев в данных решениях их использование необосновано

2020-11-19 22:44 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-24 08:55 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-24 10:54 UTC, dosandk commented
@HitriySprut а как на счет комментариев в предыдущих задачах? Я бы попросил Вас их исправить

2020-11-24 10:56 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    if(row.images) rowCells.push(`<div class="sortable-table__cell"><img class="sortable-table-image" alt="Image" src="${row.images[0].url}"></div>`);
нельзя напрямую обращаться к свойствам `row`, ведь у нас динамический конфиг, который передается в компонент. Именя и `id` колонок, которые должна нарисовать компонента могут быть любыми. Попробуйте это исправить - сделать метод не завязанным на имена колонок

2020-11-24 10:57 UTC, dosandk requested changes
поправьте пожалуйста решение SortableTable

2020-11-27 20:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-27 21:23 UTC, HitriySprut commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    if(row.images) rowCells.push(`<div class="sortable-table__cell"><img class="sortable-table-image" alt="Image" src="${row.images[0].url}"></div>`);
Извините,что не исправила еще предыдущие замечания, я не сообразила, что при новых пушах в мой репозиторий все автоматически добавляется в пулл-реквест=/ я просто еще не успела всё доделать=/

2020-11-27 22:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-30 12:09 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    if(row.images) rowCells.push(`<div class="sortable-table__cell"><img class="sortable-table-image" alt="Image" src="${row.images[0].url}"></div>`);
@HitriySprut доделывайте конечно, нет проблем.

2020-11-30 12:09 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathNodes = path.split('.');
good 👍

2020-11-30 12:09 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (obj === undefined) return undefined;
здесь можно просто `return` без явной предачи `undefined`

2020-11-30 12:10 UTC, dosandk approved these changes
good 👍

2020-11-30 12:11 UTC, merged